# Generated by Django 4.2.18 on 2025-01-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_entregador_produto_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='horarioChegada',
            field=models.DateField(blank=True, null=True, verbose_name='Horário de Chegada do Entregador'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horarioDataPedido',
            field=models.DateField(blank=True, null=True, verbose_name='Horário do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ACE', 'Em Aceitação'), ('PRE', 'Em Preparo'), ('PRT', 'Pronto'), ('ENV', 'Enviado'), ('ENT', 'Entregue'), ('CAN', 'Cancelado')], default='ACE', max_length=3),
        ),
    ]
